const YOUTUBE_API_KEY = process.env.NEXT_PUBLIC_YOUTUBE_API_KEY || process.env.YOUTUBE_API_KEY
const MEE_YOH_PLAYLIST_ID = process.env.NEXT_PUBLIC_MEE_YOH_PLAYLIST_ID || process.env.MEE_YOH_PLAYLIST_ID

const ENV = {
    YOUTUBE_API_KEY: YOUTUBE_API_KEY,
    MEE_YOH_PLAYLIST_ID: MEE_YOH_PLAYLIST_ID
}

export default ENV